insert into produto(nome,preco,descricao,ativo) values('BIG MAC QUARTERAO',22.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('BIG MAC FELIZ',25.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('BIG MAC BOM DIA',19.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('BIG MAC QUEIJO CHADDAR',42.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('BIG MAC QUEIJO MUSSARELO',28.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('BIG MAC DUPLO QUEIJO CHADDAR',52.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('BIG MAC DUPLO QUEIJO MUSSARELO',33.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('BIG MAC FELIZ DUPLO QUEIJO',92.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('BIG MAC QUARTERAO EM DOBRO',42.90,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('PIZZA DE CALABRESA',12.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('PIZZA DE MUSSARELA ',12.00,'pao, carne, mussarela, chaddar, tomate, alface , molho big mac','true');
insert into produto(nome,preco,descricao,ativo) values('ACAI TA TIJELA ',12.00,'acai , banana, morango, leite condensado, leite ninho','true');
insert into produto(nome,preco,descricao,ativo) values('PICOLE MASTER ',12.00,'leite e chocolate','true');
insert into produto(nome,preco,descricao,ativo) values('PICANHA NA CHAPA ',129.00,'picanha de sol, arroz, feijao tropeiro, mandioca, vinagrete','true');
insert into produto(nome,preco,descricao,ativo) values('COCA COLA  ',12.00,'2 litros','true');
insert into produto(nome,preco,descricao,ativo) values('FANTA LARANJA ',12.00,'2 litros','true');
insert into produto(nome,preco,descricao,ativo) values('FANTA UVA ',12.00,' 2 litros','true');
insert into produto(nome,preco,descricao,ativo) values('CERVEJA HEINEKEN',12.00,'330 ML','true');
insert into produto(nome,preco,descricao,ativo) values('CERVEJA SOL ',12.00,'330 ML','true');
insert into produto(nome,preco,descricao,ativo) values('SUCO LARANJA ',12.00,'500 ML','true');

